-- contract=postgres-finance version=1 status=DRAFT owner_task=FIN-010 decisions=D-04,D-12,D-13,D-20,D-25,D-35 last_changed=2026-09-28
-- Reference DDL for the PostgreSQL schema `finance` (lane K5, domain FIN). Alembic migrations must converge to it
-- (schema-diff test, CONVENTIONS §1/§10). Contributing tasks: FIN-010-S01 (periods, close, statements),
-- FIN-101-S01 (billing references), FIN-105-S01 (customer-approved rate tables), FIN-009-S11 (reconciliation runs
-- and explanations), FIN-104-S02 (maturity overrides), FIN-107-S01 (correction cases, prior-period adjustments).
--
-- Rules applied (CONVENTIONS §10):
--   * every table is tenant-owned: tenant_id, id (UUIDv7 generated by the application), created_at, updated_at,
--     revision, PRIMARY KEY (tenant_id, id), composite foreign keys including tenant_id, tenant-leading indexes;
--   * ROW LEVEL SECURITY ENABLE + FORCE with the SEC RLS standard policy (fallback template of the contract brief
--     until K2 publishes contracts/postgres/platform*.sql; replace the policy body with K2's template verbatim);
--   * status columns are text + CHECK generated from contracts/state-machines/<machine>.yaml;
--   * money and rates are numeric(38,12) (NUMBER(38,12) in Snowflake); never float;
--   * JSONB only for versioned, schema-validated documents (*_json + *_schema_version);
--   * no analytical fact mirror (PRD §57): charges, attribution rows, reconciliation differences and statement lines
--     live in Snowflake; this schema stores identifiers, statuses, bounded counts, issued-document totals and
--     references to Snowflake publications (pub_seq) and CONFIG versions.
--
-- Cross-lane references kept as logical columns (no FK because the target file belongs to another lane; the lead
-- adds the FKs when the files are merged — see contracts/_handoffs/K5.md):
--   tenant_id            -> tenant.tenant(id)                         (K2)
--   *_by (member ids)    -> tenant.membership(tenant_id, id)          (K2)  -- never e-mail or names (D-10)
--   organization_id      -> connection.organization(tenant_id, id)    (K3)
--   account_id           -> connection.account(tenant_id, id)         (K3)  -- account inventory incl. unconnected
--   approval_id          -> K2 approval object (SEC Appendix C.4, machine `approval`)
--   config_publication_id-> K2 config publication record (CTL-005-S03)
--   pub_seq              -> Snowflake PUBLICATION.PUBLICATION(pub_seq) (K4, ADR-014)
--
-- Requires extension btree_gist (exclusion constraint on rate lines). Created here idempotently; the platform
-- baseline (K2/K1) should own extension creation.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS finance;

COMMENT ON SCHEMA finance IS 'FIN control plane: periods, close, statements, billing references, approved rate tables, reconciliation runs/explanations, corrections. Owner lane K5. No analytical fact mirror.';

-- =====================================================================================================================
-- 1. Tenant finance policy (FIN-010-S02, FIN-107-S02, FIN-009 C5 policy, ADR-009 RECORD retention)
-- =====================================================================================================================

CREATE TABLE finance.close_policy (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    close_requires_second_approver    boolean       NOT NULL DEFAULT true,
    second_approver_waiver_ack_by     uuid          NULL,
    second_approver_waiver_ack_at     timestamptz   NULL,
    c5_required_for_close             boolean       NOT NULL DEFAULT true,
    c5_required_for_reconciled        boolean       NOT NULL DEFAULT false,
    min_account_day_coverage          numeric(38,12) NOT NULL DEFAULT 1,
    restate_abs_threshold             numeric(38,12) NOT NULL DEFAULT 100,
    restate_rel_threshold             numeric(38,12) NOT NULL DEFAULT 0.005,
    close_preview_ttl_seconds         integer       NOT NULL DEFAULT 86400,
    record_retention_days             integer       NOT NULL DEFAULT 400,
    config_publication_id             uuid          NULL,
    published_config_version          bigint        NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT close_policy_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT close_policy_one_per_tenant UNIQUE (tenant_id),
    CONSTRAINT close_policy_coverage_ck CHECK (min_account_day_coverage >= 0 AND min_account_day_coverage <= 1),
    CONSTRAINT close_policy_abs_ck CHECK (restate_abs_threshold >= 0),
    CONSTRAINT close_policy_rel_ck CHECK (restate_rel_threshold >= 0 AND restate_rel_threshold <= 1),
    CONSTRAINT close_policy_ttl_ck CHECK (close_preview_ttl_seconds BETWEEN 3600 AND 86400),
    CONSTRAINT close_policy_retention_ck CHECK (record_retention_days BETWEEN 400 AND 2557),
    -- Owner question Q3: the second approver may be waived only with an explicit tenant-owner acknowledgement.
    CONSTRAINT close_policy_waiver_ck CHECK (
        close_requires_second_approver
        OR (second_approver_waiver_ack_by IS NOT NULL AND second_approver_waiver_ack_at IS NOT NULL)
    ),
    CONSTRAINT close_policy_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.close_policy IS 'Owner FIN-010-S02/FIN-107-S02. One row per tenant. Published to CONFIG.FINANCE_POLICY (kind FINANCE_POLICY) through the D-04 config publisher; dbt period roll-up (FIN-009-S10) reads the published version.';
COMMENT ON COLUMN finance.close_policy.second_approver_waiver_ack_by IS 'Membership id of the tenant Owner who acknowledged the waiver (INTERNAL id; never a name).';
COMMENT ON COLUMN finance.close_policy.min_account_day_coverage IS 'Minimum share (0..1) of eligible (account, day) pairs of the period with contiguous charge-authority coverage before close (default 1 = complete).';
COMMENT ON COLUMN finance.close_policy.restate_abs_threshold IS 'Materiality: restatement is proposed when |delta| >= max(restate_abs_threshold, restate_rel_threshold x |closed period total|) in the period currency (owner Q4 default 100 / 0.005).';
COMMENT ON COLUMN finance.close_policy.record_retention_days IS 'S3 Object Lock GOVERNANCE retention for RECORD artifacts (statements, references): default max(400 d, contract), up to 7 years (ADR-009 amendment item 5, owner Q7).';

-- =====================================================================================================================
-- 2. Maturity policy overrides (FIN-104-S02)
-- =====================================================================================================================

CREATE TABLE finance.maturity_policy_override (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    source_id                         text          NOT NULL,
    organization_id                   uuid          NULL,
    account_id                        uuid          NULL,
    base_policy_version               text          NOT NULL,
    data_final_horizon_hours          integer       NULL,
    attribution_base_hours            integer       NULL,
    statement_timeout_cap_hours       integer       NULL,
    month_stability_days              integer       NULL,
    direction                         text          NOT NULL,
    evidence_file_id                  uuid          NULL,
    reason                            text          NOT NULL,
    status                            text          NOT NULL DEFAULT 'PROPOSED',
    effective_from                    timestamptz   NOT NULL,
    proposed_by                       uuid          NOT NULL,
    decided_by                        uuid          NULL,
    decided_at                        timestamptz   NULL,
    approval_id                       uuid          NULL,
    config_publication_id             uuid          NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT maturity_policy_override_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT maturity_policy_override_source_ck CHECK (source_id ~ '^[A-Z][A-Z0-9_]{2,63}$'),
    CONSTRAINT maturity_policy_override_direction_ck CHECK (direction IN ('STRICTER', 'LOOSER_WITH_EVIDENCE')),
    CONSTRAINT maturity_policy_override_evidence_ck CHECK (direction = 'STRICTER' OR evidence_file_id IS NOT NULL),
    CONSTRAINT maturity_policy_override_status_ck CHECK (status IN ('PROPOSED', 'ACTIVE', 'REJECTED', 'RETIRED')),
    CONSTRAINT maturity_policy_override_hours_ck CHECK (
        (data_final_horizon_hours IS NULL OR data_final_horizon_hours BETWEEN 1 AND 2160)
        AND (attribution_base_hours IS NULL OR attribution_base_hours BETWEEN 1 AND 2160)
        AND (statement_timeout_cap_hours IS NULL OR statement_timeout_cap_hours BETWEEN 0 AND 168)
        AND (month_stability_days IS NULL OR month_stability_days BETWEEN 1 AND 60)
    ),
    CONSTRAINT maturity_policy_override_any_ck CHECK (
        num_nonnulls(data_final_horizon_hours, attribution_base_hours, statement_timeout_cap_hours, month_stability_days) >= 1
    ),
    CONSTRAINT maturity_policy_override_decider_ck CHECK (decided_by IS NULL OR decided_by <> proposed_by),
    CONSTRAINT maturity_policy_override_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.maturity_policy_override IS 'Owner FIN-104-S02. Per-tenant maturity overrides over ref_source_maturity_policy; only stricter values or evidence-backed looser values; maker-checker; published as CONFIG kind MATURITY_POLICY_OVERRIDE. Never weakens close evidence (ADR-003).';
CREATE UNIQUE INDEX maturity_policy_override_active_uq ON finance.maturity_policy_override
    (tenant_id, source_id, organization_id, account_id) NULLS NOT DISTINCT WHERE status = 'ACTIVE';

-- =====================================================================================================================
-- 3. Evidence files (FIN-101-S02/S03; also rate-table and explanation evidence). Machine: finance_evidence_file
-- =====================================================================================================================

CREATE TABLE finance.evidence_file (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    purpose                           text          NOT NULL,
    organization_id                   uuid          NULL,
    filename                          text          NOT NULL,
    content_type                      text          NOT NULL,
    declared_size_bytes               bigint        NOT NULL,
    size_bytes                        bigint        NULL,
    declared_sha256                   char(64)      NOT NULL,
    sha256                            char(64)      NULL,
    object_key                        text          NOT NULL,
    status                            text          NOT NULL DEFAULT 'UPLOAD_PENDING',
    scan_engine                       text          NULL,
    scan_result_detail                text          NULL,
    scanned_at                        timestamptz   NULL,
    object_lock_mode                  text          NOT NULL DEFAULT 'GOVERNANCE',
    retain_until                      timestamptz   NULL,
    legal_hold                        boolean       NOT NULL DEFAULT false,
    uploaded_by                       uuid          NOT NULL,
    upload_expires_at                 timestamptz   NOT NULL,
    upload_completed_at               timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT evidence_file_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT evidence_file_purpose_ck CHECK (purpose IN ('REFERENCE_ORIGINAL', 'RATE_TABLE_EVIDENCE', 'EXPLANATION_EVIDENCE', 'MATURITY_OVERRIDE_EVIDENCE')),
    CONSTRAINT evidence_file_content_type_ck CHECK (content_type IN ('application/pdf', 'text/csv')),
    CONSTRAINT evidence_file_size_ck CHECK (declared_size_bytes BETWEEN 1 AND 20971520 AND (size_bytes IS NULL OR size_bytes BETWEEN 1 AND 20971520)),
    CONSTRAINT evidence_file_sha_ck CHECK (declared_sha256 ~ '^[0-9a-f]{64}$' AND (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$')),
    CONSTRAINT evidence_file_key_ck CHECK (object_key ~ '^tenants/[0-9a-f-]{36}/finance/(references/[0-9a-f-]{36}/v[1-9][0-9]{0,5}/original|evidence/[0-9a-f-]{36}/original)[.](pdf|csv)$'),
    CONSTRAINT evidence_file_status_ck CHECK (status IN ('UPLOAD_PENDING', 'SCAN_PENDING', 'CLEAN', 'INFECTED', 'EXPIRED')),
    CONSTRAINT evidence_file_clean_ck CHECK (status <> 'CLEAN' OR (sha256 IS NOT NULL AND size_bytes IS NOT NULL AND scanned_at IS NOT NULL)),
    CONSTRAINT evidence_file_lock_ck CHECK (object_lock_mode = 'GOVERNANCE'),
    CONSTRAINT evidence_file_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.evidence_file IS 'Owner FIN-101-S02/S03. Customer-supplied finance documents in the tenant evidence prefix (SSE-KMS tenant key, Object Lock GOVERNANCE per ADR-009 amendment; retention from close_policy.record_retention_days). Downloads only through the SEC-006-S08 broker (30 s presigned URL).';
COMMENT ON COLUMN finance.evidence_file.filename IS 'privacy=CUSTOMER_METADATA. Sanitized display name (max 255 chars, no path separators); never used in the object key.';
COMMENT ON COLUMN finance.evidence_file.scan_result_detail IS 'privacy=INTERNAL. Scanner signature name only; never file content.';
COMMENT ON COLUMN finance.evidence_file.object_key IS 'privacy=INTERNAL. Server-built key; tenant prefix enforced by the IAM prefix policy (FIN-101-S02).';
ALTER TABLE finance.evidence_file ADD CONSTRAINT evidence_file_filename_ck CHECK (char_length(filename) BETWEEN 1 AND 255 AND filename !~ '[/\\]');
CREATE INDEX evidence_file_status_ix ON finance.evidence_file (tenant_id, status, upload_expires_at);
CREATE INDEX evidence_file_sha_ix ON finance.evidence_file (tenant_id, sha256) WHERE sha256 IS NOT NULL;

-- =====================================================================================================================
-- 4. Customer-approved rate tables (FIN-105-S01). Machine: rate_table
-- =====================================================================================================================

CREATE TABLE finance.rate_table (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    lineage_id                        uuid          NOT NULL,
    version                           integer       NOT NULL,
    organization_id                   uuid          NOT NULL,
    name                              text          NOT NULL,
    currency                          char(3)       NOT NULL,
    rate_source                       text          NOT NULL DEFAULT 'CUSTOMER_APPROVED',
    contract_reference                text          NULL,
    effective_from                    date          NOT NULL,
    effective_to                      date          NULL,
    status                            text          NOT NULL DEFAULT 'DRAFT',
    evidence_file_id                  uuid          NULL,
    content_sha256                    char(64)      NULL,
    line_count                        integer       NOT NULL DEFAULT 0,
    supersedes_id                     uuid          NULL,
    submitted_by                      uuid          NULL,
    submitted_at                      timestamptz   NULL,
    approved_by                       uuid          NULL,
    approved_at                       timestamptz   NULL,
    self_approved                     boolean       NOT NULL DEFAULT false,
    approval_id                       uuid          NULL,
    rejected_by                       uuid          NULL,
    rejected_at                       timestamptz   NULL,
    rejection_reason                  text          NULL,
    config_publication_id             uuid          NULL,
    activated_at                      timestamptz   NULL,
    superseded_at                     timestamptz   NULL,
    created_by                        uuid          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT rate_table_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT rate_table_lineage_version_uq UNIQUE (tenant_id, lineage_id, version),
    CONSTRAINT rate_table_version_ck CHECK (version >= 1),
    CONSTRAINT rate_table_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT rate_table_source_ck CHECK (rate_source IN ('CUSTOMER_APPROVED', 'DEMO_FIXTURE')),
    CONSTRAINT rate_table_period_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT rate_table_status_ck CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'ACTIVE', 'REJECTED', 'SUPERSEDED', 'DISCARDED')),
    CONSTRAINT rate_table_sha_ck CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT rate_table_submit_ck CHECK (status IN ('DRAFT', 'DISCARDED') OR (submitted_by IS NOT NULL AND submitted_at IS NOT NULL AND content_sha256 IS NOT NULL AND evidence_file_id IS NOT NULL)),
    CONSTRAINT rate_table_approve_ck CHECK (status NOT IN ('APPROVED', 'ACTIVE', 'SUPERSEDED') OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND approval_id IS NOT NULL)),
    -- SEC Appendix C.4: price.manage four-eyes; self-approval only when a single eligible approver exists, and flagged.
    CONSTRAINT rate_table_maker_checker_ck CHECK (approved_by IS NULL OR approved_by <> submitted_by OR self_approved),
    CONSTRAINT rate_table_supersedes_fk FOREIGN KEY (tenant_id, supersedes_id) REFERENCES finance.rate_table (tenant_id, id),
    CONSTRAINT rate_table_evidence_fk FOREIGN KEY (tenant_id, evidence_file_id) REFERENCES finance.evidence_file (tenant_id, id),
    CONSTRAINT rate_table_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.rate_table IS 'Owner FIN-105-S01/S03. Versioned customer-approved rate table (reseller / no-billing-access tenants, G-FIN-13). Approved versions are published to CONFIG.PRICE_RATE (K2 kind table) with rate_source CUSTOMER_APPROVED; money priced with it is labelled CUSTOMER_APPROVED_RATE and is never BILLED_SOURCE. DEMO_FIXTURE is accepted only for tenant.kind = DEMO (provenance guard, FIN-002-S10).';
COMMENT ON COLUMN finance.rate_table.name IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.rate_table.contract_reference IS 'privacy=CUSTOMER_METADATA. Customer contract / order-form reference as typed by the maker.';
COMMENT ON COLUMN finance.rate_table.rejection_reason IS 'privacy=CUSTOMER_METADATA. Free text; must not contain personal data (UI hint).';
CREATE UNIQUE INDEX rate_table_one_open_version_uq ON finance.rate_table (tenant_id, lineage_id) WHERE status IN ('DRAFT', 'SUBMITTED', 'APPROVED');
CREATE UNIQUE INDEX rate_table_one_active_version_uq ON finance.rate_table (tenant_id, lineage_id) WHERE status = 'ACTIVE';
CREATE INDEX rate_table_org_ix ON finance.rate_table (tenant_id, organization_id, status, effective_from);

CREATE TABLE finance.rate_table_line (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    rate_table_id                     uuid          NOT NULL,
    line_no                           integer       NOT NULL,
    service_family                    text          NULL,
    service_type                      text          NULL,
    rating_type                       text          NULL,
    region                            text          NULL,
    unit                              text          NOT NULL,
    rate                              numeric(38,12) NOT NULL,
    tb_unit                           text          NULL,
    effective_from                    date          NOT NULL,
    effective_to                      date          NULL,
    source_row_no                     integer       NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT rate_table_line_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT rate_table_line_no_uq UNIQUE (tenant_id, rate_table_id, line_no),
    CONSTRAINT rate_table_line_table_fk FOREIGN KEY (tenant_id, rate_table_id) REFERENCES finance.rate_table (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT rate_table_line_key_ck CHECK (service_family IS NOT NULL OR service_type IS NOT NULL),
    CONSTRAINT rate_table_line_family_ck CHECK (service_family IS NULL OR service_family ~ '^[A-Z][A-Z0-9_]{1,63}$'),
    CONSTRAINT rate_table_line_type_ck CHECK (service_type IS NULL OR service_type ~ '^[A-Z][A-Z0-9_ -]{1,63}$'),
    CONSTRAINT rate_table_line_unit_ck CHECK (unit IN ('CREDIT', 'TB_MONTH', 'TB')),
    CONSTRAINT rate_table_line_rate_ck CHECK (rate >= 0),
    CONSTRAINT rate_table_line_tb_unit_ck CHECK ((unit = 'CREDIT' AND tb_unit IS NULL) OR (unit IN ('TB_MONTH', 'TB') AND tb_unit IN ('DECIMAL_TB_1E12', 'BINARY_TIB_2E40'))),
    CONSTRAINT rate_table_line_period_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT rate_table_line_revision_ck CHECK (revision >= 1),
    -- FIN-105-S01: overlapping effective periods for the same key are rejected (half-open [from, to)).
    CONSTRAINT rate_table_line_no_overlap_ex EXCLUDE USING gist (
        tenant_id WITH =,
        rate_table_id WITH =,
        (coalesce(service_family, '')) WITH =,
        (coalesce(service_type, '')) WITH =,
        (coalesce(rating_type, '')) WITH =,
        (coalesce(region, '')) WITH =,
        (daterange(effective_from, effective_to, '[)')) WITH &&
    )
);
COMMENT ON TABLE finance.rate_table_line IS 'Owner FIN-105-S01. One rate per (service_family|service_type, rating_type, region, unit) and effective interval [effective_from, effective_to). Rate is a decimal string in the API, numeric(38,12) here; "2,91" comma decimals are rejected at import unless a locale is declared (FIN-105-S02).';
COMMENT ON COLUMN finance.rate_table_line.region IS 'privacy=CUSTOMER_METADATA. Snowflake region identifier as typed (e.g. AWS_EU_WEST_1).';

CREATE TABLE finance.rate_simulation (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    rate_table_id                     uuid          NOT NULL,
    rate_table_revision               bigint        NOT NULL,
    window_start                      date          NOT NULL,
    window_end                        date          NOT NULL,
    status                            text          NOT NULL DEFAULT 'QUEUED',
    requested_by                      uuid          NOT NULL,
    simulation_input_ref              text          NULL,
    result_json                       jsonb         NULL,
    result_schema_version             integer       NULL,
    error_code                        text          NULL,
    started_at                        timestamptz   NULL,
    finished_at                       timestamptz   NULL,
    expires_at                        timestamptz   NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT rate_simulation_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT rate_simulation_table_fk FOREIGN KEY (tenant_id, rate_table_id) REFERENCES finance.rate_table (tenant_id, id),
    CONSTRAINT rate_simulation_window_ck CHECK (window_end > window_start AND window_end - window_start <= 366),
    CONSTRAINT rate_simulation_status_ck CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT rate_simulation_result_ck CHECK ((result_json IS NULL) = (result_schema_version IS NULL)),
    CONSTRAINT rate_simulation_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.rate_simulation IS 'Owner FIN-105-S06. Draft-rate simulation job (202 pattern). Writes only to the D-04 SIMULATION_INPUT schema, never to published tables. result_json = per (family, currency) bounded delta summary validated by data/contracts/finance/rate_table.schema.json#/$defs/simulation_result (schema_version 1).';
CREATE INDEX rate_simulation_table_ix ON finance.rate_simulation (tenant_id, rate_table_id, created_at DESC);

-- =====================================================================================================================
-- 5. Billing references (FIN-101-S01/S06). Machine: billing_reference
-- =====================================================================================================================

CREATE TABLE finance.billing_reference_lineage (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    reference_type                    text          NOT NULL,
    document_number                   text          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    created_by                        uuid          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT billing_reference_lineage_pk PRIMARY KEY (tenant_id, id),
    -- FIN-101-S06 duplicate guard on (tenant, org, reference_type, document_number, period) -> 409 FIN_REFERENCE_DUPLICATE.
    CONSTRAINT billing_reference_lineage_document_uq UNIQUE (tenant_id, organization_id, reference_type, document_number, period),
    CONSTRAINT billing_reference_lineage_type_ck CHECK (reference_type IN ('SNOWFLAKE_USAGE_STATEMENT', 'SNOWFLAKE_INVOICE', 'RESELLER_INVOICE', 'MARKETPLACE_INVOICE', 'MANUAL_TOTALS')),
    CONSTRAINT billing_reference_lineage_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT billing_reference_lineage_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT billing_reference_lineage_docno_ck CHECK (char_length(document_number) BETWEEN 1 AND 128),
    CONSTRAINT billing_reference_lineage_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.billing_reference_lineage IS 'Owner FIN-101-S06. Identity of one external billing document across its versions (v1, v2 ...). MANUAL_TOTALS use a synthetic document_number chosen by the maker.';
COMMENT ON COLUMN finance.billing_reference_lineage.document_number IS 'privacy=CUSTOMER_METADATA. Invoice / statement number as printed.';

CREATE TABLE finance.billing_reference (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    lineage_id                        uuid          NOT NULL,
    version                           integer       NOT NULL,
    organization_id                   uuid          NOT NULL,
    contract_number                   text          NULL,
    reference_type                    text          NOT NULL,
    document_number                   text          NOT NULL,
    document_date                     date          NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    declared_total                    numeric(38,12) NOT NULL,
    itemised                          boolean       NOT NULL DEFAULT true,
    lines_total                       numeric(38,12) NULL,
    in_scope_total                    numeric(38,12) NULL,
    line_count                        integer       NOT NULL DEFAULT 0,
    original_file_id                  uuid          NULL,
    parse_status                      text          NOT NULL DEFAULT 'NOT_APPLICABLE',
    parser_version                    text          NULL,
    parse_error_count                 integer       NOT NULL DEFAULT 0,
    status                            text          NOT NULL DEFAULT 'DRAFT',
    content_sha256                    char(64)      NULL,
    supersedes_id                     uuid          NULL,
    submitted_by                      uuid          NULL,
    submitted_at                      timestamptz   NULL,
    approved_by                       uuid          NULL,
    approved_at                       timestamptz   NULL,
    approval_id                       uuid          NULL,
    rejected_by                       uuid          NULL,
    rejected_at                       timestamptz   NULL,
    rejection_reason                  text          NULL,
    config_publication_id             uuid          NULL,
    activated_at                      timestamptz   NULL,
    superseded_at                     timestamptz   NULL,
    created_by                        uuid          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT billing_reference_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT billing_reference_version_uq UNIQUE (tenant_id, lineage_id, version),
    CONSTRAINT billing_reference_lineage_fk FOREIGN KEY (tenant_id, lineage_id) REFERENCES finance.billing_reference_lineage (tenant_id, id),
    CONSTRAINT billing_reference_supersedes_fk FOREIGN KEY (tenant_id, supersedes_id) REFERENCES finance.billing_reference (tenant_id, id),
    CONSTRAINT billing_reference_file_fk FOREIGN KEY (tenant_id, original_file_id) REFERENCES finance.evidence_file (tenant_id, id),
    CONSTRAINT billing_reference_version_ck CHECK (version >= 1 AND (version = 1) = (supersedes_id IS NULL)),
    CONSTRAINT billing_reference_type_ck CHECK (reference_type IN ('SNOWFLAKE_USAGE_STATEMENT', 'SNOWFLAKE_INVOICE', 'RESELLER_INVOICE', 'MARKETPLACE_INVOICE', 'MANUAL_TOTALS')),
    CONSTRAINT billing_reference_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT billing_reference_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT billing_reference_parse_ck CHECK (parse_status IN ('NOT_APPLICABLE', 'PENDING', 'PARSED', 'FAILED')),
    CONSTRAINT billing_reference_status_ck CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'ACTIVE', 'REJECTED', 'SUPERSEDED', 'DISCARDED')),
    CONSTRAINT billing_reference_sha_ck CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    -- FIN-101-S05: document total check is exact (sum of lines = declared total) before submission.
    CONSTRAINT billing_reference_submit_ck CHECK (
        status IN ('DRAFT', 'DISCARDED')
        OR (submitted_by IS NOT NULL AND submitted_at IS NOT NULL AND content_sha256 IS NOT NULL
            AND line_count >= 1 AND lines_total = declared_total AND in_scope_total IS NOT NULL)
    ),
    CONSTRAINT billing_reference_approve_ck CHECK (status NOT IN ('APPROVED', 'ACTIVE', 'SUPERSEDED') OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND approval_id IS NOT NULL)),
    CONSTRAINT billing_reference_maker_checker_ck CHECK (approved_by IS NULL OR approved_by <> submitted_by),
    CONSTRAINT billing_reference_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.billing_reference IS 'Owner FIN-101-S01/S06. One version of an external billing reference (usage statement, invoice, reseller/marketplace invoice, manual totals). Approved versions are published immutably to CONFIG.BILLING_REFERENCE(+_LINE) (kind BILLING_REFERENCE) and read by ledger.fct_billing_reference; C5 compares against ACTIVE versions only. PDF files are evidence only (no OCR in R1).';
COMMENT ON COLUMN finance.billing_reference.contract_number IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.billing_reference.document_number IS 'privacy=CUSTOMER_METADATA. Copied from the lineage for query convenience; immutable.';
COMMENT ON COLUMN finance.billing_reference.in_scope_total IS 'Sum of lines classified CONSUMPTION, SUPPORT, ADJUSTMENT, CREDIT_NOTE, MARKETPLACE (C5 scope); TAX, CAPACITY_PURCHASE and OTHER are out of scope and listed separately.';
COMMENT ON COLUMN finance.billing_reference.rejection_reason IS 'privacy=CUSTOMER_METADATA.';
CREATE UNIQUE INDEX billing_reference_one_open_version_uq ON finance.billing_reference (tenant_id, lineage_id) WHERE status IN ('DRAFT', 'SUBMITTED', 'APPROVED');
CREATE UNIQUE INDEX billing_reference_one_active_version_uq ON finance.billing_reference (tenant_id, lineage_id) WHERE status = 'ACTIVE';
CREATE INDEX billing_reference_scope_ix ON finance.billing_reference (tenant_id, organization_id, period, currency, status);

CREATE TABLE finance.billing_reference_file_claim (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    file_sha256                       char(64)      NOT NULL,
    lineage_id                        uuid          NOT NULL,
    first_reference_id                uuid          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT billing_reference_file_claim_pk PRIMARY KEY (tenant_id, id),
    -- FIN-101-S06 duplicate guard on file sha256: the same file may be reused by later versions of the same lineage
    -- only; another lineage inserting the same hash gets 409 FIN_REFERENCE_DUPLICATE.
    CONSTRAINT billing_reference_file_claim_sha_uq UNIQUE (tenant_id, file_sha256),
    CONSTRAINT billing_reference_file_claim_sha_ck CHECK (file_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT billing_reference_file_claim_lineage_fk FOREIGN KEY (tenant_id, lineage_id) REFERENCES finance.billing_reference_lineage (tenant_id, id),
    CONSTRAINT billing_reference_file_claim_ref_fk FOREIGN KEY (tenant_id, first_reference_id) REFERENCES finance.billing_reference (tenant_id, id),
    CONSTRAINT billing_reference_file_claim_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.billing_reference_file_claim IS 'Owner FIN-101-S06. First lineage that attached a given original file hash; enforces the file-level duplicate guard across lineages.';

CREATE TABLE finance.billing_reference_line (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    billing_reference_id              uuid          NOT NULL,
    line_no                           integer       NOT NULL,
    line_class                        text          NOT NULL,
    description                       text          NULL,
    service_family                    text          NULL,
    account_locator                   text          NULL,
    quantity                          numeric(38,12) NULL,
    quantity_unit                     text          NULL,
    amount                            numeric(38,12) NOT NULL,
    source_row_no                     integer       NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT billing_reference_line_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT billing_reference_line_no_uq UNIQUE (tenant_id, billing_reference_id, line_no),
    CONSTRAINT billing_reference_line_ref_fk FOREIGN KEY (tenant_id, billing_reference_id) REFERENCES finance.billing_reference (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT billing_reference_line_class_ck CHECK (line_class IN ('CONSUMPTION', 'TAX', 'CAPACITY_PURCHASE', 'SUPPORT', 'CREDIT_NOTE', 'ADJUSTMENT', 'MARKETPLACE', 'OTHER')),
    -- FIN-101-S05 sign rule: credit notes are negative (or zero).
    CONSTRAINT billing_reference_line_sign_ck CHECK (line_class <> 'CREDIT_NOTE' OR amount <= 0),
    CONSTRAINT billing_reference_line_family_ck CHECK (service_family IS NULL OR service_family ~ '^[A-Z][A-Z0-9_]{1,63}$'),
    CONSTRAINT billing_reference_line_qty_ck CHECK ((quantity IS NULL) = (quantity_unit IS NULL)),
    CONSTRAINT billing_reference_line_unit_ck CHECK (quantity_unit IS NULL OR quantity_unit IN ('CREDIT', 'TB', 'TB_MONTH', 'UNIT')),
    CONSTRAINT billing_reference_line_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.billing_reference_line IS 'Owner FIN-101-S01/S05. Classified reference lines (bounded, one document). Entered manually or produced by the versioned usage-statement CSV parser (FIN-101-S04).';
COMMENT ON COLUMN finance.billing_reference_line.description IS 'privacy=CUSTOMER_METADATA. Line text as printed; the UI warns not to type personal data.';
COMMENT ON COLUMN finance.billing_reference_line.account_locator IS 'privacy=CUSTOMER_METADATA. Snowflake account locator when the document itemises accounts.';

-- =====================================================================================================================
-- 6. Financial periods (FIN-010-S01). Machine: period
-- =====================================================================================================================

CREATE TABLE finance.financial_period (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    period_start                      date          NOT NULL,
    period_end                        date          NOT NULL,
    status                            text          NOT NULL DEFAULT 'OPEN',
    stable_at                         timestamptz   NULL,
    stability_policy_version          text          NULL,
    current_close_id                  uuid          NULL,
    current_close_version             integer       NOT NULL DEFAULT 0,
    open_correction_case_count        integer       NOT NULL DEFAULT 0,
    latest_reconciliation_run_id      uuid          NULL,
    reconciliation_status             text          NULL,
    reconciliation_status_reason      text          NULL,
    reconciled_pub_seq                bigint        NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT financial_period_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT financial_period_scope_uq UNIQUE (tenant_id, organization_id, period, currency),
    CONSTRAINT financial_period_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT financial_period_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    -- UTC calendar month, half-open [period_start, period_end) (G-FIN-26).
    CONSTRAINT financial_period_bounds_ck CHECK (
        period_start = to_date(period || '-01', 'YYYY-MM-DD')
        AND period_end = (period_start + interval '1 month')::date
    ),
    CONSTRAINT financial_period_status_ck CHECK (status IN ('OPEN', 'MONTH_STABLE', 'CLOSE_PREVIEWED', 'CLOSING_ARTIFACTS', 'CLOSED', 'RESTATEMENT_PROPOSED', 'RESTATED')),
    CONSTRAINT financial_period_stable_ck CHECK (status = 'OPEN' OR stable_at IS NOT NULL),
    CONSTRAINT financial_period_close_ck CHECK (
        (status IN ('CLOSED', 'RESTATEMENT_PROPOSED') AND current_close_version >= 1 AND current_close_id IS NOT NULL)
        OR (status = 'RESTATED' AND current_close_version >= 2 AND current_close_id IS NOT NULL)
        OR status IN ('OPEN', 'MONTH_STABLE', 'CLOSE_PREVIEWED', 'CLOSING_ARTIFACTS')
    ),
    CONSTRAINT financial_period_open_ck CHECK (status NOT IN ('OPEN', 'MONTH_STABLE', 'CLOSE_PREVIEWED') OR current_close_version = 0),
    CONSTRAINT financial_period_recon_ck CHECK (
        (reconciliation_status IS NULL AND reconciliation_status_reason IS NOT NULL)
        OR (reconciliation_status IN ('PENDING', 'MATCHED', 'WARNING', 'FAILED') AND reconciliation_status_reason IS NULL)
        OR (reconciliation_status IS NULL AND reconciliation_status_reason IS NULL AND latest_reconciliation_run_id IS NULL)
    ),
    CONSTRAINT financial_period_recon_reason_ck CHECK (reconciliation_status_reason IS NULL OR reconciliation_status_reason IN ('NOT_APPLICABLE', 'TRIAL_ACCOUNT', 'INSUFFICIENT_DATA', 'NOT_YET_AVAILABLE')),
    CONSTRAINT financial_period_counts_ck CHECK (open_correction_case_count >= 0),
    CONSTRAINT financial_period_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.financial_period IS 'Owner FIN-010-S01. One row per (tenant, organization, UTC month, currency). status = machine `period` (contracts/state-machines/period.yaml); API period_state (OPEN|MONTH_STABLE|CLOSED|RESTATED) is a projection defined in data/contracts/finance/period_state_machine.md. Created by the finance worker when the first charge of the month/currency is published, or eagerly on the 1st of each month for every organization x currency seen in the last 3 months.';
COMMENT ON COLUMN finance.financial_period.reconciliation_status IS 'Worst required-control status of the latest completed reconciliation run for this period and currency (canonical enum). NULL + reconciliation_status_reason when no required control is applicable (e.g. TRIAL_ACCOUNT, D-35).';
COMMENT ON COLUMN finance.financial_period.reconciled_pub_seq IS 'Publication at which every required control was MATCHED or approved-WARNING (RECONCILED is per period and publication, FIN-009-S10); NULL when not reconciled or reverted by a newer revision.';
CREATE INDEX financial_period_status_ix ON finance.financial_period (tenant_id, status, period);
CREATE INDEX financial_period_org_ix ON finance.financial_period (tenant_id, organization_id, period DESC);

-- =====================================================================================================================
-- 7. Close requests (preview) and close records (FIN-010-S03/S04/S06). Machines: period_close_request, period
-- =====================================================================================================================

CREATE TABLE finance.period_close_request (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    period_id                         uuid          NOT NULL,
    period_revision_at_request        bigint        NOT NULL,
    status                            text          NOT NULL DEFAULT 'PREVIEW_PENDING',
    requested_by                      uuid          NOT NULL,
    requested_at                      timestamptz   NOT NULL DEFAULT now(),
    request_note                      text          NULL,
    preconditions_json                jsonb         NULL,
    preconditions_schema_version      integer       NULL,
    manifest_json                     jsonb         NULL,
    manifest_schema_version           integer       NULL,
    manifest_sha256                   char(64)      NULL,
    statement_preview_json            jsonb         NULL,
    statement_preview_schema_version  integer       NULL,
    preview_ready_at                  timestamptz   NULL,
    preview_expires_at                timestamptz   NULL,
    decided_by                        uuid          NULL,
    decided_at                        timestamptz   NULL,
    decision_note                     text          NULL,
    approval_id                       uuid          NULL,
    failure_code                      text          NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT period_close_request_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT period_close_request_period_fk FOREIGN KEY (tenant_id, period_id) REFERENCES finance.financial_period (tenant_id, id),
    CONSTRAINT period_close_request_status_ck CHECK (status IN ('PREVIEW_PENDING', 'PREVIEWED', 'APPROVED', 'REJECTED', 'EXPIRED', 'STALE', 'FAILED')),
    CONSTRAINT period_close_request_docs_ck CHECK (
        ((preconditions_json IS NULL) = (preconditions_schema_version IS NULL))
        AND ((manifest_json IS NULL) = (manifest_schema_version IS NULL))
        AND ((statement_preview_json IS NULL) = (statement_preview_schema_version IS NULL))
    ),
    CONSTRAINT period_close_request_preview_ck CHECK (
        status IN ('PREVIEW_PENDING', 'FAILED')
        OR (manifest_json IS NOT NULL AND manifest_sha256 IS NOT NULL AND statement_preview_json IS NOT NULL
            AND preview_ready_at IS NOT NULL AND preview_expires_at IS NOT NULL)
        OR (status IN ('REJECTED', 'STALE') AND manifest_json IS NULL)
    ),
    CONSTRAINT period_close_request_ttl_ck CHECK (preview_expires_at IS NULL OR preview_expires_at <= preview_ready_at + interval '24 hours'),
    CONSTRAINT period_close_request_sha_ck CHECK (manifest_sha256 IS NULL OR manifest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT period_close_request_decided_ck CHECK (status NOT IN ('APPROVED', 'REJECTED') OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT period_close_request_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.period_close_request IS 'Owner FIN-010-S03/S04. Close request with its preview: preconditions (ordered remedy list), freeze-set manifest (data/contracts/finance/close_manifest.schema.json, schema_version 1) and statement preview (data/contracts/finance/statement.schema.json, schema_version 1). Preview expires after close_policy.close_preview_ttl_seconds (max 24 h).';
COMMENT ON COLUMN finance.period_close_request.request_note IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.period_close_request.decision_note IS 'privacy=CUSTOMER_METADATA.';
CREATE UNIQUE INDEX period_close_request_one_active_uq ON finance.period_close_request (tenant_id, period_id) WHERE status IN ('PREVIEW_PENDING', 'PREVIEWED');
CREATE INDEX period_close_request_expiry_ix ON finance.period_close_request (tenant_id, status, preview_expires_at);

CREATE TABLE finance.period_close (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    period_id                         uuid          NOT NULL,
    close_version                     integer       NOT NULL,
    kind                              text          NOT NULL,
    close_request_id                  uuid          NULL,
    correction_case_id                uuid          NULL,
    predecessor_close_id              uuid          NULL,
    status                            text          NOT NULL DEFAULT 'CLOSING_ARTIFACTS',
    manifest_json                     jsonb         NOT NULL,
    manifest_schema_version           integer       NOT NULL,
    manifest_sha256                   char(64)      NOT NULL,
    ledger_pub_seq                    bigint        NOT NULL,
    revision_set_sha256               char(64)      NOT NULL,
    crosswalk_version                 text          NOT NULL,
    maturity_policy_version           text          NOT NULL,
    rate_version_set_sha256           char(64)      NOT NULL,
    fx_version                        text          NULL,
    control_run_id                    uuid          NOT NULL,
    requested_by                      uuid          NOT NULL,
    requested_at                      timestamptz   NOT NULL,
    approved_by                       uuid          NOT NULL,
    approved_at                       timestamptz   NOT NULL,
    second_approver_waived            boolean       NOT NULL DEFAULT false,
    approval_id                       uuid          NOT NULL,
    publication_status                text          NOT NULL DEFAULT 'PENDING',
    config_publication_id             uuid          NULL,
    artifact_status                   text          NOT NULL DEFAULT 'PENDING',
    pin_status                        text          NOT NULL DEFAULT 'PENDING',
    publication_pin_ref               text          NULL,
    completed_at                      timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT period_close_pk PRIMARY KEY (tenant_id, id),
    -- FIN-010-S01/S10: one close record per (tenant, org, period, currency, version); concurrent approvals yield one.
    CONSTRAINT period_close_version_uq UNIQUE (tenant_id, period_id, close_version),
    CONSTRAINT period_close_period_fk FOREIGN KEY (tenant_id, period_id) REFERENCES finance.financial_period (tenant_id, id),
    CONSTRAINT period_close_request_fk FOREIGN KEY (tenant_id, close_request_id) REFERENCES finance.period_close_request (tenant_id, id),
    CONSTRAINT period_close_predecessor_fk FOREIGN KEY (tenant_id, predecessor_close_id) REFERENCES finance.period_close (tenant_id, id),
    CONSTRAINT period_close_version_ck CHECK (close_version >= 1),
    CONSTRAINT period_close_kind_ck CHECK (
        (kind = 'CLOSE' AND close_version = 1 AND close_request_id IS NOT NULL AND correction_case_id IS NULL AND predecessor_close_id IS NULL)
        OR (kind = 'RESTATEMENT' AND close_version >= 2 AND correction_case_id IS NOT NULL AND predecessor_close_id IS NOT NULL)
    ),
    CONSTRAINT period_close_status_ck CHECK (status IN ('CLOSING_ARTIFACTS', 'COMPLETED')),
    CONSTRAINT period_close_sub_status_ck CHECK (publication_status IN ('PENDING', 'DONE') AND artifact_status IN ('PENDING', 'DONE') AND pin_status IN ('PENDING', 'DONE')),
    CONSTRAINT period_close_completed_ck CHECK (
        status <> 'COMPLETED' OR (publication_status = 'DONE' AND artifact_status = 'DONE' AND pin_status = 'DONE' AND completed_at IS NOT NULL)
    ),
    CONSTRAINT period_close_sha_ck CHECK (
        manifest_sha256 ~ '^[0-9a-f]{64}$' AND revision_set_sha256 ~ '^[0-9a-f]{64}$' AND rate_version_set_sha256 ~ '^[0-9a-f]{64}$'
    ),
    -- ADR-003 amendment / G-FIN-11: approver differs from requester unless the audited tenant waiver applies.
    CONSTRAINT period_close_maker_checker_ck CHECK (approved_by <> requested_by OR second_approver_waived),
    CONSTRAINT period_close_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.period_close IS 'Owner FIN-010-S06 (v1) / FIN-107-S03 (restatement v>=2). Immutable close record with the pinned freeze set (manifest_json: data/contracts/finance/close_manifest.schema.json). Approve writes this row in one PG transaction (status CLOSING_ARTIFACTS), then the idempotent D-04 insert (CONFIG.PERIOD_CLOSE kind PERIOD_CLOSE, key close_id), then the S3 Object Lock upload keyed by close_id and the PUBLICATION.PIN (K4); COMPLETED when all three confirm. Business columns are never updated after insert except the three sub-statuses, publication refs, status and completed_at.';
CREATE INDEX period_close_status_ix ON finance.period_close (tenant_id, status, created_at);

ALTER TABLE finance.financial_period
    ADD CONSTRAINT financial_period_current_close_fk FOREIGN KEY (tenant_id, current_close_id) REFERENCES finance.period_close (tenant_id, id);

-- =====================================================================================================================
-- 8. Statements (FIN-010-S05) and artifacts (Object Lock GOVERNANCE, RECORD class)
-- =====================================================================================================================

CREATE TABLE finance.statement (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    lineage_id                        uuid          NOT NULL,
    statement_version                 integer       NOT NULL,
    predecessor_statement_id          uuid          NULL,
    period_id                         uuid          NOT NULL,
    close_id                          uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    minor_unit                        smallint      NOT NULL,
    rounding_algorithm                text          NOT NULL DEFAULT 'SIGNED_LARGEST_REMAINDER_V1',
    total_exact                       numeric(38,12) NOT NULL,
    total_rounded                     numeric(38,12) NOT NULL,
    prior_period_adjustment_total     numeric(38,12) NOT NULL DEFAULT 0,
    line_count                        integer       NOT NULL,
    excluded_trial_account_count      integer       NOT NULL DEFAULT 0,
    statement_json_sha256             char(64)      NOT NULL,
    status                            text          NOT NULL DEFAULT 'GENERATING',
    issued_at                         timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT statement_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT statement_close_uq UNIQUE (tenant_id, close_id),
    CONSTRAINT statement_version_uq UNIQUE (tenant_id, lineage_id, statement_version),
    CONSTRAINT statement_period_fk FOREIGN KEY (tenant_id, period_id) REFERENCES finance.financial_period (tenant_id, id),
    CONSTRAINT statement_close_fk FOREIGN KEY (tenant_id, close_id) REFERENCES finance.period_close (tenant_id, id),
    CONSTRAINT statement_predecessor_fk FOREIGN KEY (tenant_id, predecessor_statement_id) REFERENCES finance.statement (tenant_id, id),
    CONSTRAINT statement_version_ck CHECK (statement_version >= 1 AND (statement_version = 1) = (predecessor_statement_id IS NULL)),
    CONSTRAINT statement_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT statement_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT statement_minor_unit_ck CHECK (minor_unit BETWEEN 0 AND 4),
    CONSTRAINT statement_rounding_ck CHECK (rounding_algorithm = 'SIGNED_LARGEST_REMAINDER_V1'),
    CONSTRAINT statement_counts_ck CHECK (line_count >= 0 AND excluded_trial_account_count >= 0),
    CONSTRAINT statement_sha_ck CHECK (statement_json_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT statement_status_ck CHECK (status IN ('GENERATING', 'ISSUED')),
    CONSTRAINT statement_issued_ck CHECK (status <> 'ISSUED' OR issued_at IS NOT NULL),
    CONSTRAINT statement_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.statement IS 'Owner FIN-010-S05 / FIN-107-S03. Issued financial-period statement header (one per close version). Lines live in Snowflake CONFIG.STATEMENT_LINE -> ledger.fct_statement_line and in the JSON/CSV/PDF artifacts; totals are issued-document values (not an analytical mirror). A closed statement is immutable and re-downloads byte-identical (sha256).';

CREATE TABLE finance.statement_artifact (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    statement_id                      uuid          NOT NULL,
    format                            text          NOT NULL,
    object_key                        text          NOT NULL,
    sha256                            char(64)      NULL,
    size_bytes                        bigint        NULL,
    object_lock_mode                  text          NOT NULL DEFAULT 'GOVERNANCE',
    retain_until                      timestamptz   NOT NULL,
    status                            text          NOT NULL DEFAULT 'PENDING',
    stored_at                         timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT statement_artifact_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT statement_artifact_format_uq UNIQUE (tenant_id, statement_id, format),
    CONSTRAINT statement_artifact_statement_fk FOREIGN KEY (tenant_id, statement_id) REFERENCES finance.statement (tenant_id, id),
    CONSTRAINT statement_artifact_format_ck CHECK (format IN ('JSON', 'CSV', 'PDF')),
    CONSTRAINT statement_artifact_key_ck CHECK (object_key ~ '^tenants/[0-9a-f-]{36}/finance/closes/[0-9a-f-]{36}/statement[.](json|csv|pdf)$'),
    CONSTRAINT statement_artifact_lock_ck CHECK (object_lock_mode = 'GOVERNANCE'),
    CONSTRAINT statement_artifact_status_ck CHECK (status IN ('PENDING', 'STORED')),
    CONSTRAINT statement_artifact_stored_ck CHECK (status <> 'STORED' OR (sha256 ~ '^[0-9a-f]{64}$' AND size_bytes > 0 AND stored_at IS NOT NULL)),
    CONSTRAINT statement_artifact_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.statement_artifact IS 'Owner FIN-010-S05/S06. Statement renderings stored under tenants/{tenant_id}/finance/closes/{close_id}/statement.{json,csv,pdf} with S3 Object Lock GOVERNANCE (RECORD class, ADR-009 amendment; break-glass bypass only). CSV is formula-neutralized by the API-102 writer; PDF rendered by the RPT renderer. Download through SEC-006-S08 only.';

-- =====================================================================================================================
-- 9. Reconciliation runs, control results and explanations (FIN-009-S02/S11/S12). Machines: reconciliation_run,
--    reconciliation_explanation
-- =====================================================================================================================

CREATE TABLE finance.reconciliation_run (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NULL,
    control_ids                       text[]        NOT NULL DEFAULT ARRAY['C1','C2','C3','C4','C5','C6','C7','C8','C9']::text[],
    trigger                           text          NOT NULL,
    requested_by                      uuid          NULL,
    status                            text          NOT NULL DEFAULT 'QUEUED',
    ledger_pub_seq                    bigint        NULL,
    build_id                          text          NULL,
    orchestrator_run_ref              text          NULL,
    outcome_status                    text          NULL,
    outcome_status_reason             text          NULL,
    is_reconciled                     boolean       NULL,
    error_code                        text          NULL,
    queued_at                         timestamptz   NOT NULL DEFAULT now(),
    started_at                        timestamptz   NULL,
    finished_at                       timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT reconciliation_run_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT reconciliation_run_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT reconciliation_run_currency_ck CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT reconciliation_run_controls_ck CHECK (
        cardinality(control_ids) BETWEEN 1 AND 10
        AND control_ids <@ ARRAY['C1','C2','C3','C4','C5','C6','C7','C8','C9','CS_ADJUSTMENT_RULE']::text[]
    ),
    CONSTRAINT reconciliation_run_trigger_ck CHECK (trigger IN ('MANUAL', 'SCHEDULED_NIGHTLY', 'PUBLICATION', 'REFERENCE_ACTIVATED', 'EXPLANATION_DECIDED', 'CLOSE_PREVIEW')),
    CONSTRAINT reconciliation_run_requester_ck CHECK ((trigger IN ('MANUAL', 'CLOSE_PREVIEW')) = (requested_by IS NOT NULL)),
    CONSTRAINT reconciliation_run_status_ck CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'ERRORED', 'CANCELLED')),
    CONSTRAINT reconciliation_run_outcome_ck CHECK (
        (status <> 'SUCCEEDED' AND outcome_status IS NULL AND outcome_status_reason IS NULL AND is_reconciled IS NULL)
        OR (status = 'SUCCEEDED' AND is_reconciled IS NOT NULL AND ledger_pub_seq IS NOT NULL
            AND ((outcome_status IN ('PENDING', 'MATCHED', 'WARNING', 'FAILED') AND outcome_status_reason IS NULL)
                 OR (outcome_status IS NULL AND outcome_status_reason IN ('NOT_APPLICABLE', 'TRIAL_ACCOUNT'))))
    ),
    CONSTRAINT reconciliation_run_times_ck CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    CONSTRAINT reconciliation_run_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.reconciliation_run IS 'Owner FIN-009-S02/S12. Job record of one control run over (organization, UTC month, currency or all currencies) pinned to ledger_pub_seq. Computation is the dbt reconciliation selector run by the orchestrator (K4); differences live in Snowflake fct_reconciliation keyed by run_id. outcome_status = worst required-control status (canonical enum); NULL + reason when no control applies (D-35 trial-only scope).';
CREATE INDEX reconciliation_run_scope_ix ON finance.reconciliation_run (tenant_id, organization_id, period, queued_at DESC);
CREATE UNIQUE INDEX reconciliation_run_one_active_uq ON finance.reconciliation_run (tenant_id, organization_id, period, coalesce(currency, '*'), trigger) WHERE status IN ('QUEUED', 'RUNNING');

CREATE TABLE finance.reconciliation_control_result (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    run_id                            uuid          NOT NULL,
    control_id                        text          NOT NULL,
    currency                          char(3)       NOT NULL,
    status                            text          NULL,
    status_reason                     text          NULL,
    not_applicable_code               text          NULL,
    pending_reason_code               text          NULL,
    required_for_reconciled           boolean       NOT NULL,
    required_for_close                boolean       NOT NULL,
    compared_bucket_count             integer       NOT NULL DEFAULT 0,
    matched_bucket_count              integer       NOT NULL DEFAULT 0,
    explained_bucket_count            integer       NOT NULL DEFAULT 0,
    failed_bucket_count               integer       NOT NULL DEFAULT 0,
    pending_bucket_count              integer       NOT NULL DEFAULT 0,
    controls_contract_version         text          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT reconciliation_control_result_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT reconciliation_control_result_uq UNIQUE (tenant_id, run_id, control_id, currency),
    CONSTRAINT reconciliation_control_result_run_fk FOREIGN KEY (tenant_id, run_id) REFERENCES finance.reconciliation_run (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT reconciliation_control_result_control_ck CHECK (control_id IN ('C1','C2','C3','C4','C5','C6','C7','C8','C9','CS_ADJUSTMENT_RULE')),
    CONSTRAINT reconciliation_control_result_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    -- Canonical reconciliation enum only; "not applicable" is NULL + reason (CONVENTIONS §6, ledger.md).
    CONSTRAINT reconciliation_control_result_status_ck CHECK (
        (status IN ('PENDING', 'MATCHED', 'WARNING', 'FAILED') AND status_reason IS NULL AND not_applicable_code IS NULL)
        OR (status IS NULL AND status_reason IN ('NOT_APPLICABLE', 'TRIAL_ACCOUNT') AND not_applicable_code IS NOT NULL)
    ),
    CONSTRAINT reconciliation_control_result_na_ck CHECK (not_applicable_code IS NULL OR not_applicable_code IN ('ALLOCATION_DISABLED', 'TRIAL_ACCOUNT_DEMO_ONLY', 'ORGANIZATION_USAGE_UNAVAILABLE', 'NO_ESTIMATES_SUPERSEDED', 'PERIOD_NOT_CLOSED', 'NO_DETAIL_SOURCE_ENABLED', 'NO_CREDIT_FAMILIES')),
    CONSTRAINT reconciliation_control_result_pending_ck CHECK ((status = 'PENDING') = (pending_reason_code IS NOT NULL)),
    CONSTRAINT reconciliation_control_result_pending_code_ck CHECK (pending_reason_code IS NULL OR pending_reason_code IN ('INPUT_NOT_FINAL', 'INPUT_ABSENT', 'REFERENCE_MISSING', 'COVERAGE_GAP')),
    CONSTRAINT reconciliation_control_result_counts_ck CHECK (
        compared_bucket_count >= 0 AND matched_bucket_count >= 0 AND explained_bucket_count >= 0
        AND failed_bucket_count >= 0 AND pending_bucket_count >= 0
        AND matched_bucket_count + explained_bucket_count + failed_bucket_count + pending_bucket_count = compared_bucket_count
    ),
    CONSTRAINT reconciliation_control_result_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.reconciliation_control_result IS 'Owner FIN-009-S02. Per (run, control, currency) status and bounded bucket counts copied from Snowflake fct_reconciliation after the run (no amounts: deltas are read from Snowflake through the broker).';

CREATE TABLE finance.reconciliation_explanation (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    target_kind                       text          NOT NULL,
    run_id                            uuid          NOT NULL,
    control_id                        text          NOT NULL,
    organization_id                   uuid          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    difference_id                     char(64)      NULL,
    difference_grain_key              char(64)      NULL,
    difference_etag                   text          NULL,
    classification                    text          NOT NULL,
    explained_delta                   numeric(38,12) NULL,
    note                              text          NOT NULL,
    status                            text          NOT NULL DEFAULT 'SUBMITTED',
    author_id                         uuid          NOT NULL,
    submitted_at                      timestamptz   NOT NULL DEFAULT now(),
    decided_by                        uuid          NULL,
    decided_at                        timestamptz   NULL,
    decision_note                     text          NULL,
    approval_id                       uuid          NULL,
    invalidated_by_run_id             uuid          NULL,
    config_publication_id             uuid          NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT reconciliation_explanation_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT reconciliation_explanation_run_fk FOREIGN KEY (tenant_id, run_id) REFERENCES finance.reconciliation_run (tenant_id, id),
    CONSTRAINT reconciliation_explanation_kind_ck CHECK (
        (target_kind = 'DIFFERENCE' AND difference_id ~ '^[0-9a-f]{64}$' AND difference_grain_key ~ '^[0-9a-f]{64}$' AND difference_etag IS NOT NULL AND explained_delta IS NOT NULL)
        OR (target_kind = 'CONTROL' AND difference_id IS NULL AND difference_grain_key IS NULL AND difference_etag IS NULL AND explained_delta IS NULL)
    ),
    CONSTRAINT reconciliation_explanation_control_ck CHECK (control_id IN ('C1','C2','C3','C4','C5','C6','C7','C8','C9')),
    -- C6 and C7 are exact conservation controls: they can never be explained (a leak is a defect).
    CONSTRAINT reconciliation_explanation_explainable_ck CHECK (control_id NOT IN ('C6', 'C7')),
    CONSTRAINT reconciliation_explanation_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT reconciliation_explanation_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT reconciliation_explanation_class_ck CHECK (classification IN ('TIMING', 'TAX_SCOPE', 'CAPACITY_PURCHASE', 'RATE_MISMATCH', 'OVERAGE_PRICING', 'ADJUSTMENT', 'UNMAPPED_SERVICE', 'MISSING_SOURCE', 'MARKETPLACE_SEPARATE_INVOICE', 'OTHER')),
    CONSTRAINT reconciliation_explanation_note_ck CHECK (char_length(note) BETWEEN 10 AND 4000),
    CONSTRAINT reconciliation_explanation_status_ck CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'INVALIDATED')),
    CONSTRAINT reconciliation_explanation_decided_ck CHECK (status NOT IN ('APPROVED', 'REJECTED') OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT reconciliation_explanation_approval_ck CHECK (status <> 'APPROVED' OR approval_id IS NOT NULL),
    -- FIN-009-S11: author self-approval -> 409 FIN_MAKER_CHECKER_VIOLATION.
    CONSTRAINT reconciliation_explanation_maker_checker_ck CHECK (decided_by IS NULL OR decided_by <> author_id OR status IN ('WITHDRAWN', 'INVALIDATED')),
    CONSTRAINT reconciliation_explanation_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.reconciliation_explanation IS 'Owner FIN-009-S11. Classified explanation of one difference bucket (DIFFERENCE) or a control-level exception for a period (CONTROL, e.g. C5 PENDING because the reseller invoice arrives after close). Approved explanations are published to CONFIG.RECONCILIATION_EXPLANATION and turn FAILED/PENDING into WARNING (never MATCHED). They never write fct_charge (no balancing plug).';
COMMENT ON COLUMN finance.reconciliation_explanation.note IS 'privacy=CUSTOMER_METADATA. Analyst justification; must not contain personal data (UI hint).';
COMMENT ON COLUMN finance.reconciliation_explanation.decision_note IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.reconciliation_explanation.difference_etag IS 'Etag of the difference row explained (sha256 of run_id, difference_id, ledger_value, reference_value); a later run with other values invalidates the explanation.';
CREATE UNIQUE INDEX reconciliation_explanation_one_live_uq ON finance.reconciliation_explanation (tenant_id, control_id, organization_id, period, currency, coalesce(difference_grain_key, 'CONTROL')) WHERE status IN ('SUBMITTED', 'APPROVED');
CREATE INDEX reconciliation_explanation_scope_ix ON finance.reconciliation_explanation (tenant_id, organization_id, period, status);

CREATE TABLE finance.reconciliation_explanation_evidence (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    explanation_id                    uuid          NOT NULL,
    evidence_file_id                  uuid          NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT reconciliation_explanation_evidence_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT reconciliation_explanation_evidence_uq UNIQUE (tenant_id, explanation_id, evidence_file_id),
    CONSTRAINT reconciliation_explanation_evidence_expl_fk FOREIGN KEY (tenant_id, explanation_id) REFERENCES finance.reconciliation_explanation (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT reconciliation_explanation_evidence_file_fk FOREIGN KEY (tenant_id, evidence_file_id) REFERENCES finance.evidence_file (tenant_id, id),
    CONSTRAINT reconciliation_explanation_evidence_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.reconciliation_explanation_evidence IS 'Owner FIN-009-S11. Evidence files attached to an explanation (at least one CLEAN file is required before approval).';

-- =====================================================================================================================
-- 10. Corrections of closed periods (FIN-107-S01/S04). Machine: restatement
-- =====================================================================================================================

CREATE TABLE finance.correction_case (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    period_id                         uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    period                            char(7)       NOT NULL,
    currency                          char(3)       NOT NULL,
    service_family                    text          NOT NULL,
    source                            text          NOT NULL,
    detected_by_run_id                uuid          NULL,
    manual_reason                     text          NULL,
    compared_close_id                 uuid          NOT NULL,
    compared_close_pub_seq            bigint        NOT NULL,
    current_pub_seq                   bigint        NOT NULL,
    closed_amount                     numeric(38,12) NOT NULL,
    carried_forward_amount            numeric(38,12) NOT NULL DEFAULT 0,
    current_amount                    numeric(38,12) NOT NULL,
    delta                             numeric(38,12) NOT NULL,
    closed_period_total               numeric(38,12) NOT NULL,
    materiality_threshold             numeric(38,12) NOT NULL,
    is_material                       boolean       NOT NULL,
    proposed_default                  text          NOT NULL,
    status                            text          NOT NULL DEFAULT 'OPEN',
    decision                          text          NULL,
    target_accounting_period          char(7)       NULL,
    proposed_by                       uuid          NULL,
    proposed_at                       timestamptz   NULL,
    proposal_pins_sha256              char(64)      NULL,
    decided_by                        uuid          NULL,
    decided_at                        timestamptz   NULL,
    decision_note                     text          NULL,
    approval_id                       uuid          NULL,
    result_close_id                   uuid          NULL,
    merged_into_id                    uuid          NULL,
    resolved_at                       timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT correction_case_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT correction_case_period_fk FOREIGN KEY (tenant_id, period_id) REFERENCES finance.financial_period (tenant_id, id),
    CONSTRAINT correction_case_close_fk FOREIGN KEY (tenant_id, compared_close_id) REFERENCES finance.period_close (tenant_id, id),
    CONSTRAINT correction_case_result_fk FOREIGN KEY (tenant_id, result_close_id) REFERENCES finance.period_close (tenant_id, id),
    CONSTRAINT correction_case_merged_fk FOREIGN KEY (tenant_id, merged_into_id) REFERENCES finance.correction_case (tenant_id, id),
    CONSTRAINT correction_case_run_fk FOREIGN KEY (tenant_id, detected_by_run_id) REFERENCES finance.reconciliation_run (tenant_id, id),
    CONSTRAINT correction_case_period_ck CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT correction_case_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT correction_case_family_ck CHECK (service_family ~ '^[A-Z][A-Z0-9_]{1,63}$'),
    CONSTRAINT correction_case_source_ck CHECK ((source = 'C9' AND detected_by_run_id IS NOT NULL) OR (source = 'MANUAL' AND manual_reason IS NOT NULL)),
    -- Declared sign (G-FIN-10): delta = current (new) - (closed + already carried forward).
    CONSTRAINT correction_case_delta_ck CHECK (delta = current_amount - (closed_amount + carried_forward_amount)),
    CONSTRAINT correction_case_default_ck CHECK (proposed_default IN ('RESTATE', 'CARRY_FORWARD') AND (proposed_default = 'RESTATE') = is_material),
    CONSTRAINT correction_case_status_ck CHECK (status IN ('OPEN', 'PROPOSED', 'APPROVED', 'RESOLVED', 'MERGED', 'VOIDED')),
    CONSTRAINT correction_case_decision_ck CHECK (decision IS NULL OR decision IN ('RESTATE', 'CARRY_FORWARD')),
    CONSTRAINT correction_case_proposed_ck CHECK (status NOT IN ('PROPOSED', 'APPROVED', 'RESOLVED') OR (decision IS NOT NULL AND proposed_by IS NOT NULL AND proposed_at IS NOT NULL AND proposal_pins_sha256 IS NOT NULL)),
    CONSTRAINT correction_case_carry_ck CHECK ((decision = 'CARRY_FORWARD') = (target_accounting_period IS NOT NULL) OR decision IS NULL),
    CONSTRAINT correction_case_target_ck CHECK (target_accounting_period IS NULL OR (target_accounting_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND target_accounting_period > period)),
    CONSTRAINT correction_case_decided_ck CHECK (status NOT IN ('APPROVED', 'RESOLVED') OR (decided_by IS NOT NULL AND decided_at IS NOT NULL AND approval_id IS NOT NULL)),
    CONSTRAINT correction_case_maker_checker_ck CHECK (decided_by IS NULL OR decided_by <> proposed_by),
    CONSTRAINT correction_case_merged_ck CHECK ((status = 'MERGED') = (merged_into_id IS NOT NULL)),
    CONSTRAINT correction_case_restate_ck CHECK (status <> 'RESOLVED' OR decision <> 'RESTATE' OR result_close_id IS NOT NULL),
    CONSTRAINT correction_case_sha_ck CHECK (proposal_pins_sha256 IS NULL OR proposal_pins_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT correction_case_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.correction_case IS 'Owner FIN-107-S01. Closed-period correction case per (period, service_family) raised by nightly C9 (CLOSED_PERIOD_DRIFT) or manually. Idempotent: at most one live case per (period, family); a later drift for the same family while OPEN/PROPOSED is merged into it (delta recomputed; a PROPOSED case whose pins changed returns to OPEN). A RESTATE approval resolves every live case of the period (others become MERGED).';
COMMENT ON COLUMN finance.correction_case.manual_reason IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.correction_case.decision_note IS 'privacy=CUSTOMER_METADATA.';
COMMENT ON COLUMN finance.correction_case.materiality_threshold IS 'max(close_policy.restate_abs_threshold, close_policy.restate_rel_threshold x |closed_period_total|) evaluated at detection; is_material = |delta| >= threshold.';
CREATE UNIQUE INDEX correction_case_one_live_uq ON finance.correction_case (tenant_id, period_id, service_family) WHERE status IN ('OPEN', 'PROPOSED', 'APPROVED');
CREATE INDEX correction_case_status_ix ON finance.correction_case (tenant_id, status, period);

ALTER TABLE finance.period_close
    ADD CONSTRAINT period_close_correction_fk FOREIGN KEY (tenant_id, correction_case_id) REFERENCES finance.correction_case (tenant_id, id);

CREATE TABLE finance.correction_case_line (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    correction_case_id                uuid          NOT NULL,
    scope_kind                        text          NOT NULL,
    account_id                        uuid          NULL,
    usage_date                        date          NOT NULL,
    closed_amount                     numeric(38,12) NOT NULL,
    carried_forward_amount            numeric(38,12) NOT NULL DEFAULT 0,
    current_amount                    numeric(38,12) NOT NULL,
    delta                             numeric(38,12) NOT NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT correction_case_line_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT correction_case_line_uq UNIQUE NULLS NOT DISTINCT (tenant_id, correction_case_id, scope_kind, account_id, usage_date),
    CONSTRAINT correction_case_line_case_fk FOREIGN KEY (tenant_id, correction_case_id) REFERENCES finance.correction_case (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT correction_case_line_scope_ck CHECK ((scope_kind = 'ORGANIZATION' AND account_id IS NULL) OR (scope_kind = 'ACCOUNT' AND account_id IS NOT NULL)),
    CONSTRAINT correction_case_line_delta_ck CHECK (delta = current_amount - (closed_amount + carried_forward_amount) AND delta <> 0),
    CONSTRAINT correction_case_line_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.correction_case_line IS 'Owner FIN-107-S01/S04. Non-zero drift per (scope, account, usage_date) of the case family; bounded (<= accounts x days). Source for PRIOR_PERIOD_ADJUSTMENT rows on carry-forward and for restatement difference lines.';

CREATE TABLE finance.prior_period_adjustment (
    tenant_id                         uuid          NOT NULL,
    id                                uuid          NOT NULL,
    correction_case_id                uuid          NOT NULL,
    correction_case_line_id           uuid          NOT NULL,
    organization_id                   uuid          NOT NULL,
    original_period                   char(7)       NOT NULL,
    accounting_period                 char(7)       NOT NULL,
    scope_kind                        text          NOT NULL,
    account_id                        uuid          NULL,
    usage_date                        date          NOT NULL,
    service_family                    text          NOT NULL,
    currency                          char(3)       NOT NULL,
    amount                            numeric(38,12) NOT NULL,
    config_publication_id             uuid          NULL,
    published_at                      timestamptz   NULL,
    created_at                        timestamptz   NOT NULL DEFAULT now(),
    updated_at                        timestamptz   NOT NULL DEFAULT now(),
    revision                          bigint        NOT NULL DEFAULT 1,
    CONSTRAINT prior_period_adjustment_pk PRIMARY KEY (tenant_id, id),
    CONSTRAINT prior_period_adjustment_line_uq UNIQUE (tenant_id, correction_case_line_id),
    CONSTRAINT prior_period_adjustment_case_fk FOREIGN KEY (tenant_id, correction_case_id) REFERENCES finance.correction_case (tenant_id, id),
    CONSTRAINT prior_period_adjustment_line_fk FOREIGN KEY (tenant_id, correction_case_line_id) REFERENCES finance.correction_case_line (tenant_id, id),
    CONSTRAINT prior_period_adjustment_periods_ck CHECK (
        original_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND accounting_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
        AND accounting_period > original_period
        AND to_char(usage_date, 'YYYY-MM') = original_period
    ),
    CONSTRAINT prior_period_adjustment_scope_ck CHECK ((scope_kind = 'ORGANIZATION' AND account_id IS NULL) OR (scope_kind = 'ACCOUNT' AND account_id IS NOT NULL)),
    CONSTRAINT prior_period_adjustment_currency_ck CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT prior_period_adjustment_amount_ck CHECK (amount <> 0),
    CONSTRAINT prior_period_adjustment_revision_ck CHECK (revision >= 1)
);
COMMENT ON TABLE finance.prior_period_adjustment IS 'Owner FIN-107-S04. Carry-forward decision lines (immutable after insert). Published to CONFIG.PRIOR_PERIOD_ADJUSTMENT (kind CORRECTION_DECISION) and turned by dbt into fct_charge rows with basis_class PPA, entry_kind PRIOR_PERIOD_ADJUSTMENT, usage_date unchanged and accounting_period = the OPEN period of the decision. Consumption KPIs (by usage_date) exclude them; statements (by accounting period) include them.';
CREATE INDEX prior_period_adjustment_period_ix ON finance.prior_period_adjustment (tenant_id, organization_id, accounting_period, currency);

-- =====================================================================================================================
-- 11. Row level security (SEC RLS standard; ENABLE + FORCE on every table)
-- =====================================================================================================================

ALTER TABLE finance.close_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.close_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.close_policy USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.maturity_policy_override ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.maturity_policy_override FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.maturity_policy_override USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.evidence_file ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.evidence_file FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.evidence_file USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.rate_table ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.rate_table FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.rate_table USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.rate_table_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.rate_table_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.rate_table_line USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.rate_simulation ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.rate_simulation FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.rate_simulation USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.billing_reference_lineage ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.billing_reference_lineage FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.billing_reference_lineage USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.billing_reference ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.billing_reference FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.billing_reference USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.billing_reference_file_claim ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.billing_reference_file_claim FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.billing_reference_file_claim USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.billing_reference_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.billing_reference_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.billing_reference_line USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.financial_period ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.financial_period FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.financial_period USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.period_close_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.period_close_request FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.period_close_request USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.period_close ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.period_close FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.period_close USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.statement ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.statement FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.statement USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.statement_artifact ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.statement_artifact FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.statement_artifact USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.reconciliation_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.reconciliation_run FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.reconciliation_run USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.reconciliation_control_result ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.reconciliation_control_result FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.reconciliation_control_result USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.reconciliation_explanation ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.reconciliation_explanation FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.reconciliation_explanation USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.reconciliation_explanation_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.reconciliation_explanation_evidence FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.reconciliation_explanation_evidence USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.correction_case ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.correction_case FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.correction_case USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.correction_case_line ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.correction_case_line FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.correction_case_line USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE finance.prior_period_adjustment ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance.prior_period_adjustment FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON finance.prior_period_adjustment USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
